opcache.max_accelerated_files=10000

expose_php = off
upload_max_filesize = 100M
post_max_size = 108M
; memory_limit = 64M

xdebug.mode=profile
xdebug.start_with_request=trigger
xdebug.output_dir = /tmp/xprofiler
xdebug.profiler_output_name = cachegrind.out.%t.%p
xdebug.trigger_value = q1w2e3
