version: '3'
services:
  dev:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./packages:/app/packages
      - ./public:/app/public
      - ./vendor:/app/vendor
      - ./themes:/app/public/themes
      - ./xprofiler:/tmp/xprofiler
      - ./docker/apache/apache.conf:/etc/apache2/conf-available/zzz-config.conf
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini
    restart: always
    env_file:
      - ./app.env

  cli:
    image: php:8.3-cli-alpine
    volumes:
      - ./:/app
    working_dir: /app

  composer:
    image: composer:2
    volumes:
      - ./:/app
      - $SSH_AUTH_SOCK:/root/ssh-agent
      - $HOME/.ssh:/root/.ssh
      - $HOME/.composer/cache:/composer-cache
    environment:
      - SSH_AUTH_SOCK=/root/ssh-agent
      - COMPOSER_CACHE_DIR=/composer-cache
    env_file:
      - ./app.env

  composer-ci:
    image: composer:2
    volumes:
      - ./:/app
      - $HOME/.ssh:/root/.ssh
      - $HOME/.composer/cache:/composer-cache
    environment:
      - SSH_AUTH_SOCK=/root/ssh-agent
      - COMPOSER_CACHE_DIR=/composer-cache
      - ACF_PRO_KEY

  db:
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - ./db.env
    command: "mysqld --max_allowed_packet=1073741824"

  db-client:
    image: mariadb:10.11
    entrypoint:
      - "mysql"
      - "-hdb"
      - "-pwp"
      - "wp"
    depends_on:
      - db

volumes:
  db_data:
